addpath([cd '\my_exp_util'], ...
	[cd '\my_img_util'], ...
	[cd '\my_ui_util'], ...
    [cd '\main'], ...
    [cd '\codegen'], ...
	[cd '\my_vehicle_vision_util']);
addpath(genpath([cd '\thirdparty']));
addpath(genpath([cd '\my_tmp_util']));
savepath;