function h=slidevar(varname,span)
%SLIDEVAR controlling a variable with a slidebar 
% http://www.mathworks.com/matlabcentral/newsreader/view_thread/28286

% Example
%  var = 80;
%  h=slidevar('var',[10 100]);

if nargin==2
    h = figure('pos',[300 300 300 80],...
        'menubar','none',...
        'numbertitle','off',...
        'name',['Variable: ' varname]);

    hs = uicontrol(h,...
        'style','slider',...
        'pos',[10 40 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(1),...
        'callback',@sliderupdate,...
        'tag',varname);
    
    uicontrol(h,...
        'style','text',...
        'pos',[10 10 280 20],...
        'tag',['text_' varname],...
        'string',num2str(span(1)))

    if nargout==0
        clear h
    end
end

% -------------------
function sliderupdate(varargin)

ht = findobj(gcbf, 'style','text');
v = get(varargin{1},'value');
set(ht, 'string', num2str(v))
assignin('base', get(varargin{1},'tag'), v)